### ISSUE TITLE
tibber_custom integration no longer working after core update to 2024.2.1

### ISSUE THREAD

**Issue by padlefot** [Danielhiversen/home_assistant_tibber_custom#55] opened 2024-02-10 10:00 UTC
Seeing this in the logs:

Setup failed for custom integration 'tibber_custom': Requirements for tibber_custom not found: ['matplotlib'].

the camera entitiy is no longer available.

**Comment by yutani42** [comment] 2024-02-10 11:37
duplicate of #53

**Comment by padlefot** [comment] 2024-02-10 13:57
yes sorry, I should have been more vigilant

**Closed** 2024-02-13 12:00 UTC
