### ISSUE TITLE
HOW TO GET RID OFF CONSTANT WARNING for >8 months: tibber custom requirement not found ['mathplotlib']

### ISSUE THREAD

**Issue by typxxi** [Danielhiversen/home_assistant_tibber_custom#59] opened 2024-11-01 13:21 UTC
I am a tibber customer for about 8 months and since I had signed the contract the ingetration went downhill, at least my impression.

Before that signature a friend of mine had explained tibber to me. He had shown to me his homeassistant dashboard and of cause this integration and the day ahead tibber_prices for my site which was working in January / February. It had worked flawlessly at least on his side and then also on my HA installation before he had to leave the country again. 

Now each time HA has to reboot I get a tibber custom **notification and warning which I hate to see**.
```
Konfigurationswarnungen
Integration error: tibber_custom - Requirements for tibber_custom not found: ['matplotlib'].
```

which looks like this if I do the yaml examination in the developer sections
![image](https://github.com/user-attachments/assets/47e2b89b-4bb9-4fd1-b408-6a8a896693c1)

Regardless what I tried (uninstall & install) that issue came back over and over again caused by the "famous" **missing mathplotlib**

I am tired to see my notification area being blocked or occupied by false alarms by this tibber custom integration which are useless and have no value as it seems that the missing mathplotlib no longer needed cause the integration and tibber pulse generally seem to be working fine except except this boot message & error notification, which appears after every start.

BUT: this notification does not belong there - it is fooling my eyes and making me tired cause I get used to that ALWAYS ON NOTIFICATION BUBBLE I had never had before.

Hence my attention level drops and if there is A SERIOUS WARNING that 2nd message does no longer get the attention it would get if there would be like in normal usage no message when any message would pop up in your eyes. 

### **NOW I had MISSED a really IMPORTANT NOTIFICATION** which was caused by TIBBER and TIBBERS false alarms.

HOW CAN I GET RID OF THAT whole message forever ?

Any suggestions ?

**Comment by typxxi** [comment] 2024-11-02 12:58
Woud be nice if there is any way to get rid of that warning but still be able to use the custom integration as we need it - at least as long as we stay tibber customers. 

thanks a lot

**Comment by Danielhiversen** [comment] 2024-11-04 19:34
Duplicate of https://github.com/Danielhiversen/home_assistant_tibber_custom/issues/53

**Closed by Danielhiversen** 2024-11-04 19:34 UTC
